import one from "../assets/images/1.webp";
import two from "../assets/images/2.webp";
import three from "../assets/images/3.webp";
import four from "../assets/images/4.webp";
import five from "../assets/images/5.webp";
import six from "../assets/images/6.webp";
import seven from "../assets/images/7.webp";
import eight from "../assets/images/8.webp";
import nine from "../assets/images/9.webp";
import ten from "../assets/images/10.webp";
export { one, two, three, four, five, six, seven, eight, nine, ten };
